### ISSUE TITLE
WinHSPF3.1 Bug - requires timeseries to exist in output wdm

### ISSUE THREAD

**Issue by TSHAIKH78** [respec/BASINS#23]
WinHSPF 3.1 requires the existence of a timeseries in the output wdm before the model is run (assuming a previous output wdm exists). A workaround so far, is to run HSPF from HSPEXP+ (or other HSPF executable) and this seems to alleviate the issue.

**Comment by PaulDudaRESPEC** [comment]
HSPF versions 12.2 and earlier require an output wdm timeseries to exist prior to simulation.  A more recent enhancement (in pre-release versions of HSPF 12.3 and later) creates those wdm timeseries automatically.  Thus the fact that WinHSPF requires a timeseries to exist is not actually a bug but a limitation that will go away with a future release of HSPF.
