### ISSUE TITLE
[HSPEXP+] 2.0 beta 3 crashes when making calibration plots

### ISSUE THREAD

**Issue by timcera** [respec/BASINS#24]
When using the "Hydrology Calibration Statistics and Graphs" option, HSPEXP+ 2.0beta3 will crash with the following error:

![hspexp _error](https://user-images.githubusercontent.com/297142/40179879-53afb41a-59b3-11e8-9a9d-7b22ff17a6cc.png)

Seems to complete almost everything for the first calibration point, then stops.  If additional calibration points are available described in other exs files, nothing is done with them.  Since the error seems to indicate a plotting problem here are the plots that are completed:

Flow_RCH7_1990log_.png
Flow_RCH7_1990.png
Flow_RCH7_1991log_.png
Flow_RCH7_1991.png
Flow_RCH7_1992log_.png
Flow_RCH7_1992.png
Flow_RCH7_1993log_.png
Flow_RCH7_1993.png
Flow_RCH7_1994log_.png
Flow_RCH7_1994.png
Flow_RCH7_1995log_.png
Flow_RCH7_1995.png
Flow_RCH7_1996log_.png
Flow_RCH7_1996.png
Flow_RCH7_1997log_.png
Flow_RCH7_1997.png
Flow_RCH7_1998log_.png
Flow_RCH7_1998.png
Flow_RCH7_1999log_.png
Flow_RCH7_1999.png
Flow_RCH7_2000log_.png
Flow_RCH7_2000.png
Flow_RCH7_2001log_.png
Flow_RCH7_2001.png
Flow_RCH7_2002log_.png
Flow_RCH7_2002.png
Flow_RCH7_2003log_.png
Flow_RCH7_2003.png
Flow_RCH7_cumDif.png
Flow_RCH7_cum.png
Flow_RCH7_dur.png
Flow_RCH7_Error_LZS.png
Flow_RCH7_Error_ObsFlow.png
Flow_RCH7_Error_UZS.png
Flow_RCH7log_.png
Flow_RCH7.png
Flow_RCH7_scatDay_log.png
Flow_RCH7_scatDay.png

**Comment by mishranurag** [comment]
HSPEXP+ also produces a log file. Please look at the end of the log file to see where exactly does it crash, and let me know.

Thanks

**Comment by mishranurag** [comment]
This issue has been fixed.
