### ISSUE TITLE
[HSPEXP+] Model QA/QC INTFW Value Not Read Correctly

### ISSUE THREAD

**Issue by mishranurag** [respec/BASINS#35]
My model had INTFW values ranging from 1 to 3, but the QA/QC report suggests that the values are 0.75 for all operations.

**Comment by PaulDudaRESPEC** [comment]
I have not been able to reproduce this problem.  Do you have the UCI you can send?

**Comment by mishranurag** [comment]
I tried it today and could not reproduce the bug either.
