### ISSUE TITLE
Can't run HSPEXP+ Number of Site are not in the correct format

### ISSUE THREAD

**Issue by kqasem** [respec/BASINS#36]
Hi,
I am trying to run hydrology calibration using HSPEXP+. I added both observed and simulated flows to the WDM. When hitting start, I get an error saying the number of sites are not in the correct format.
Any insights? 

Thanks
Karoline Qasem, PhD

**Comment by mishranurag** [comment]
Feel free to email me at amishra@ds-intl.biz if you want to resolve
this issue.
~A
***********************************
Anurag Mishra

**Comment by PaulDudaRESPEC** [comment]
Could you give us some more details about how you set up your EXS file(s)?  And which version of HSPEXP+ you are running?

**Comment by kqasem** [comment]
Thanks @mishranurag I will sure email you. @PaulDudaRESPEC , are you referring to the ".exs" file? if yes, then i created it through WinHSPF --> calibration --> selected the observed and simulated reaches I want to calibrate. Then, a .exs was created. I am attaching a screen shot to the file.

![Capture](https://user-images.githubusercontent.com/36547773/56133714-b7602800-5f52-11e9-97a5-b970c794fe9b.JPG)

I am using HSPEXP + version 2.0

Please let me know if you have any thoughts.  

Thanks a lot!

Karoline Qasem, PhD

**Comment by mishranurag** [comment]
The name of WDM file is 9 characters. That has moved the line 2 by one character to the right. You should rename the WDM file so that it has less than or equal to eight characters and move the values on second line by 1 character to the left.

**Comment by kqasem** [comment]
Awesome! Thanks so much. To confirm 3 pm central?
