### ISSUE TITLE
[HSPEXP+] Function LocateTheTimeSeries in CookieCuttergraphs returns entire TimeSeries

### ISSUE THREAD

**Issue by mishranurag** [respec/BASINS#39]
This function is used in Regan Plots, and the diurnal analysis of DO and Heat. However, this function returns the entire time series instead of the period selected on the main HSPEXP+ interface.

**Comment by PaulDudaRESPEC** [comment]
Added a 'subset by date' after each use of LocateTheTimeSeries to address issues in Regan Plots and Diurnal Analysis
