### ISSUE TITLE
[HSPEXP+] The version 3.1 beta2 doesn't come with HSPF executables.

### ISSUE THREAD

**Issue by mishranurag** [respec/BASINS#43]

**Comment by PaulDudaRESPEC** [comment]
Did you download and install HSPEXP+3.1SetUp062020.exe from https://github.com/respec/BASINS/releases?  That works for me.  Maybe you have some security settings that are not allowing the installation of exes?

**Comment by mishranurag** [comment]
I did that a couple of hours back on a computer that did not have any
previous installation of HSPEXP+.

~A
***********************************
Anurag Mishra

**Comment by PaulDudaRESPEC** [comment]
So you do that and the result is a folder with a bunch of DLLs and supporting files, but no HSPEXP+.exe?

**Comment by mishranurag** [comment]
This folder does not have WinHSPFLt.exe in it.

C:\Program Files (x86)\HSPEXP+\WinHSPFLt

~A
***********************************
Anurag Mishra

**Comment by PaulDudaRESPEC** [comment]
Oh, that is much clearer.  I'll add it and post a new one shortly.

**Comment by PaulDudaRESPEC** [comment]
I posted a new installer just now.  That should resolve the issue.
