### ISSUE TITLE
Updating PWAT-PARM2

### ISSUE THREAD

**Issue by kqasem** [respec/BASINS#45]
Hey,
I created an HSPF model using BASINS. The default PWAT-PARM2 table groups operations together and I need to assign different parameters for different operations. 
![image](https://user-images.githubusercontent.com/36547773/98166120-8afd5b00-1eac-11eb-9ccb-4e8ba9140a74.png)

When I do so in WinHSPF, the table gets messed up (see the images). Any thoughts on how to ungroup operations?
![image](https://user-images.githubusercontent.com/36547773/98166088-7f119900-1eac-11eb-97e8-c247892bd6c2.png)

Thanks a lot

Karoline

**Comment by PaulDudaRESPEC** [comment]
Hi Karoline,
It's probably easiest to do that in a text editor, like Notepad.  Just be careful not to include any tab characters -- just use the spacebar to line up your columns appropriately.
Paul

**Comment by kqasem** [comment]
Thanks, Paul for your reply. 
I think it won't be efficient if you have 230 watersheds; even when grouping some of them together. I created a python script and put the text in a format ready for the UCI. 
Please keep me posted if any new WinHSPF updates considered this issue. Appreciate your hard work!

Best,
Karoline
