### ISSUE TITLE
SARA Timeseries Utility DSN

### ISSUE THREAD

**Issue by gracekye** [respec/BASINS#49]
According to the WDMutil manual, the data set numbers for precipitation is from 11 to 191. 
However, I have 12 precipitation datasets, so can I use DSNs beyond 191-- 211, 231, 251, so on?

![DSN](https://user-images.githubusercontent.com/104831596/166438013-244c7d3b-d9b4-46c4-9fcc-23222b3cfdd7.png)

**Comment by PaulDudaRESPEC** [comment]
Sure, that numbering is just a convention used in BASINS, so you can extend it however you wish.
